root: true
extends:
  - remcohaszing
  - remcohaszing/typechecking
rules:
  jsdoc/check-indentation: off

overrides:
  - files:
      - '*.md/*.js'
    rules:
      no-empty-function: off
      no-undef: off
